[package]
name = "telos-translator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#antelope-client = { git = "https://github.com/telosnetwork/antelope-rs.git" }
antelope-client = { path = "../antelope-rs/crates/antelope" }
clap = { version = "4.5.6", features = ["derive"] }
dashmap = "5.5.3"
eyre = "0.6.5"
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
tokio-tungstenite = "0.23.0"
futures-util = "0.3.30"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
