[package]
name = "telos-translator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antelope-client = { git = "https://github.com/telosnetwork/antelope-rs.git", branch = "finish_table_rows_params" }
#alloy = { version = "0.2.1", features = ["k256"] }
alloy = "0.2.1"
alloy-rlp = "0.3.8"
alloy-consensus = "0.2.1"
bytes = "1.4.0"
num-bigint = "0.4.5"
clap = { version = "4.5.6", features = ["derive"] }
dashmap = "5.5.3"
k256 = { version = "0.13.3", features = ["ecdsa"] }
eyre = "0.6.5"
moka = { version = "0.12.7", features = ["sync"] }
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio-tungstenite = "0.23.0"
futures-util = "0.3.30"
ruint = "0.3.0"
rlp = "0.5.2"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
log = "0.4.21"
toml = "0.8.15"
lazy_static = "1.5.0"
hex = "0.4.3"
reth-trie-common = { git = "https://github.com/telosnetwork/telos-reth.git", version = "1.0.5" }

[dev-dependencies]
async-trait = "0.1.80"
chrono = "0.4.38"
num-traits = "0.2.19"
reqwest = { version = "0.12.5", features = ["json"] }
testcontainers = "0.21.0"
thiserror = "1.0.63"

[features]
bad_sig_padding = []