[package]
name = "telos-consensus-client"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
alloy-primitives = "0.6"
reth-primitives = { path = "../telos-reth/crates/primitives", features = [ "telos" ]}
reth-rpc-types = { path = "../telos-reth/crates/rpc/rpc-types" }
reth-rpc-types-compat = { path = "../telos-reth/crates/rpc/rpc-types-compat" }
csv = "1.3.0"
chrono = "0.4.33"
reqwest = {  version = "0.11.23", features = ["json"] }
clap = {  version = "4.4.18", features = ["derive"] }
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.8"
rand = "0.8.5"
zeroize = "1.7.0"
tokio = { version = "1.35.1", features = ["full"] }
hex = "0.4.3"
jsonwebtoken = "9.2.0"
serde_json = "1.0.111"
alloy-rlp = "0.3"
#arrowbatch = "1.9"
arrowbatch = { git = "https://github.com/telosnetwork/arrowbatch-rs.git", branch = "mut_refactor" }
