[package]
name = "telos-consensus-client"
version = "0.1.0"
edition = "2021"

[dependencies]
alloy-primitives = "0.6.2"
reth-primitives = { path = "../telos-reth/crates/primitives" }
reth-rpc-types = { path = "../telos-reth/crates/rpc/rpc-types" }
csv = "1.3.0"
chrono = "0.4.33"
reqwest = "0.11.23"
clap = {  version = "4.4.18", features = ["derive"] }
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.8"