[package]
name = "telos-consensus-client"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
log = "0.4"
env_logger = "0.10"
alloy-primitives = { version = "0.6", features = [ "serde" ] }
reth-primitives = { git = "https://github.com/telosnetwork/telos-reth", branch = "versioning-and-nix", features = [ "telos" ]}
reth-rpc-types = { git = "https://github.com/telosnetwork/telos-reth", branch = "versioning-and-nix" }
reth-rpc-types-compat = {git = "https://github.com/telosnetwork/telos-reth", branch = "versioning-and-nix" }
reth-telos = { git = "https://github.com/telosnetwork/telos-reth", branch = "versioning-and-nix" }
csv = "1.3.0"
chrono = "0.4.33"
reqwest = {  version = "0.11.23", features = ["json"] }
clap = {  version = "4.4.18", features = ["derive"] }
serde = { version = "1.0.196", features = ["derive"] }
toml = "0.8.8"
rand = "0.8.5"
zeroize = "1.7.0"
tokio = { version = "1.35.1", features = ["full"] }
hex = "0.4.3"
jsonwebtoken = "9.2.0"
serde_json = "1.0.111"
alloy-rlp = "0.3"
arrowbatch = "1.14.0"
base64 = "0.22.1"
antelope-client = { git = "https://github.com/telosnetwork/antelope-rs", branch = "serialization" }
thiserror = "1.0.62"