[package]
name = "telos-translator-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
antelope-client = { git = "https://github.com/telosnetwork/antelope-rs.git", branch = "serialization" }
# antelope-client = { path = "../antelope-rs/crates/antelope" }
alloy = { git = "https://github.com/alloy-rs/alloy", rev = "v0.1.1" }
alloy-rlp = { git = "https://github.com/alloy-rs/rlp", rev = "v0.3.5" }
alloy-consensus = { git = " https://github.com/alloy-rs/alloy", rev = "v0.1.1" }
bytes = "1.4.0"
num-bigint = "0.4.5"
clap = { version = "4.5.6", features = ["derive"] }
dashmap = "5.5.3"
k256 = { version = "0.13.3", features = ["ecdsa"] }
eyre = "0.6.5"
moka = { version = "0.12.7", features = ["sync"] }
tokio = { version = "1.38.0", features = ["rt", "rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio-tungstenite = "0.23.0"
futures-util = "0.3.30"
ruint = "0.3.0"
rlp = "0.5.2"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
log = "0.4.21"
toml = "0.8.15"
lazy_static = "1.5.0"
hex = "0.4.3"

[dev-dependencies]
async-trait = "0.1.80"
