# Check src/types/env.rs for testnet/mainnet values to use

# These are basic mainnet values, all optional values are left out and will use default values
chain_id = "36fe7024b760365e3970b7b403e161811c1e626edd68460272fcdfa276272563"
start_block = 0
block_delta = 36
prev_hash = 0
http_endpoint = "http://192.168.0.20:8883"
ship_endpoint = "http://192.168.0.20:18989"
